# This is a basic workflow to help you get started with Actions

name: Interrogate Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  interrogate_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/api.py
          fail-under: 100
  interrogate_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/config.py
          fail-under: 100
  interrogate_crud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/crud.py
          fail-under: 100
  interrogate_database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/database.py
          fail-under: 100
  interrogate_exceptions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/exceptions
          fail-under: 100
  interrogate_models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/models
          fail-under: 100
  interrogate_routers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/routers
          fail-under: 100
  interrogate_utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          path: backend/app/utils
          fail-under: 100
